name: fennec
deployment:
  image:
    registry: "blancahot" #p21d12501503001.azurecr.io
    # registryPort: 8080
    repository: "fennec" #rbs-devops/essence
    pullPolicy: Always
    pullSecrets: acr-auth
    tag: "latest"
  replicas: 1
  rollingUpdate:
    maxUnavailable: 25%
    # maxSurge: 1
    # progressDeadlineSeconds: 600
    # revisionHistoryLimit: 5
  limits:
    cpu: 1
    memory: 2Gi
  node: ip-10-0-140-211.eu-west-2.compute.internal
service:
  omitClusterIP: true
  type: ClusterIP
  protocol: TCP
  ports:
    app: 8080
    # exporter: ???
ingress:
  enable: true
  host: gal.fennec.io
