# This is a basic workflow to help you get started with Actions

name: build-and-push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ feature/ci-cd ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: create workspace
        run: |
          pwd
          mkdir -p "$GITHUB_WORKSPACE/build-workspace"
      
      - name: download artifacts-components
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          repo: Rhinops-Sela/components
          workflow: ci-cd-pipeline.yaml
          name: components
          path: ${{ github.workspace }}/build-workspace/components
          
      - name: download artifacts-backend
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          repo: Rhinops-Sela/backend
          workflow: ci-cd-pipeline.yaml
          name: dist
          path: ${{ github.workspace }}/build-workspace/backend
          
      - name: download artifacts-backend2
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          repo: Rhinops-Sela/backend
          workflow: ci-cd-pipeline.yaml
          name: node_modules
          path: ${{ github.workspace }}/build-workspace/backend
          
      - name: download artifacts-webclient
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          repo: Rhinops-Sela/webclient
          workflow: ci-cd-pipeline.yaml
          name: Publish wizard
          path: ${{ github.workspace }}/build-workspace/webclient
      

      - name: print artifact
        run: |
          echo "$GITHUB_WORKSPACE"
          cd $GITHUB_WORKSPACE/build-workspace
          ls
          cd $GITHUB_WORKSPACE/build-workspace/components
          ls
          cd $GITHUB_WORKSPACE/build-workspace/backend
          ls
          cd $GITHUB_WORKSPACE/build-workspace/webclient
          ls
          
