# This is a basic workflow to help you get started with Actions

name: build-and-push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ feature/ci-cd ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      #download artifacts-components
      - name: Archive production artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          workflow: ci-cd-pipeline.yaml
          name: components
          path: ${{ github.workspace }}

      - name: print artifact
        run: |
          echo "$GITHUB_WORKSPACE"
          cd $GITHUB_WORKSPACE
          ls
