name: devops-CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the develop branch
  repository_dispatch:
    types: [components_built]
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
      # Publish artifacts-devops
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: metadata
        path: metadata/
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: blancahot
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: blancahot/fennec-base:${{ github.run_number }},blancahot/fennec-base:latest,blancahot/fennec-base:develop
        file: DockerfileBase





