name: devops-CI

on:
  pull_request:
    branches: [ feature/ci-cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
      # Publish artifacts-devops
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: metadata
        path: metadata/
      
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: fennec-base
        # Tags override for Docker image
        tags: ${{ github.run_id }}
        # Target Docker registry
        registry: 'blancahot/fennec'
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: DockerfileBase
        addLatest: true
        # Docker registry username
        username: blancahot
        # Docker registry password
        password: ${{ secrets.DOCKER_PASSWORD }}
        




