name: devops-CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the develop branch
  repository_dispatch:
#   push:
#     branches:
#       - shaharblanksela-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
      # Publish artifacts-devops
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: metadata
        path: metadata/
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: blancahot
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: blancahot/fennec-base:${{ github.run_number }},blancahot/fennec-base:latest,blancahot/fennec-base:develop
        file: DockerfileBase
        
  workflow_run_info:
    name: Information about the workflow run
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Show Information
        run: |
          echo "This workflow run is triggered by ${{ github.event_name }} ."
          echo " *****************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo " *****************************************************************************"




